[tool.poetry]
name = "hackathon2023"
version = "0.1.0"
description = "App for BrainBit"
authors = ["Yura D., Erik Z."]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
